apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.refresh_clamav_db_cron | quote }}
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          containers:
          - name: {{ template "app.fullname" . }}-refresh
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command: ["kubectl"]
            args: ["rollout", "restart", "deployment/{{ template "app.fullname" . }}"]
          restartPolicy: OnFailure
          serviceAccountName: refreshclamav
