apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3310
      protocol: TCP 
      targetPort: {{ .Values.image.port }} 
      name: {{ template "app.name" . }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
