---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: refreshclamav
  labels:
    {{- include "app.labels" . | nindent 4 }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: refreshclamav
  labels:
    {{- include "app.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "apps"
      - "extensions"
    resources:
      - "deployments"
    resourceNames:
      - {{ template "app.fullname" . }}
    verbs:
      - "patch"
      - "get"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: refreshclamav
  labels:
    {{- include "app.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: refreshclamav
roleRef:
  kind: Role
  name: refreshclamav
  apiGroup: rbac.authorization.k8s.io
