# Declare variables to be passed into your templates.

image:
  repository: ministryofjustice/data-engineering-data-extractor
  tag: v1

# Run once daily at midnight
cronJobSchedule: "0 0 * * *"
awsDefaultRegion: eu-west-2
saveEventsLog: true
enabled: false
