---
# Enable/disable the cronjob, this sets the suspend field on the cronjob spec
enabled: false

# Required: set to a service account configured with IRSA and
# appropriate IAM role for access to Analytical Platforms S3 bucket.
serviceAccountName: ""

# Run once daily at midnight
cronJobSchedule: "0 0 * * *"
awsDefaultRegion: eu-west-2
saveEventsLog: true
args: "extract_table_names.py && extract_pg_jsonl_snapshot.py && transfer_local_to_s3.sh"

# Required: set to the name of the secret where S3 destination is stored.
# Optionally set a value for destinationS3SecretKey if different from default.
destinationS3SecretName: ""
destinationS3SecretKey: destination_bucket

# Required: set to the name of secret where DB creds are stored.
# Optionally set the keys below if required.
databaseSecretName: ""
databaseAddressSecretKey: rds_instance_address
databaseNameSecretKey: database_name
databaseUsernameSecretKey: database_username
databasePasswordSecretKey: database_password

# Optional: set to the name of secret where API auth creds are stored.
dataPlatformApiAuthSecretName: ""
dataPlatformApiAuthSecretKey: auth-key

# If uploading to the data platform, the dataProductName needs to be set to
# a registered data product
dataProductName: ""

# Optional: Cronjob resource name override. The default cronjob name is the release name (truncated to 27) followed by `-data-analytics-extractor`
cronJobNameOverride: ""

fullnameOverride: ""

image:
  repository: ministryofjustice/data-engineering-data-extractor
  tag: sha-b84888b

# Optional definition of resources useful for services with more data to extract
resources: {}
