---
# Default values for generic-prometheus-alerts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Name of application, which is used to filter the alert queries, override specific resource types below.
targetApplication: ""

# To disable inclusion of ingress alerts, set to false, defaults true
ingressAlertsEnabled: true

# The alert severity label is used within Alert Manager and determines which slack channel alerts are sent to.
alertSeverity: digital-prison-service-dev

runbookUrl: https://github.com/ministryofjustice/hmpps-helm-charts/blob/main/charts/generic-prometheus-alerts/RUNBOOK.md#
grafanaUrl: https://grafana.live.cloud-platform.service.justice.gov.uk

# Alert by default will target resources uses a regex and the application name (.Values.targetApplication).
# To be more or less specific with promql queries set these overrides in the parent chart, examples:

# podTargetOverride: ".*"

# deploymentTargetOverride: ".*"

# ingressTargetOverride: ".*"

# hpaTargetOverride: ".*"

# jobTargetOverride: ".*"

# cronjobTargetOverride: ".*"

# Mod_Security normally blocks requests with http status 403 - forbidden.
# To be able to distinguish and specifically alert on mod_security blocking
# the general pattern has been to update the mod_security config to block
# using a different status code. The default is 406 but this can be overridden: 

# modSecBlockingStatusCodeOverride: "406"

extraAnnotations: {}

extraLabels:
  prometheus: cloud-platform

additionalRuleLabels: {}

# To monitor AWS SQS queues, add the name of the queue in a list like this:
# sqsAlertsQueueNames:
#   - "queue-name"
#   - "queue-name-2"

# Set the alert threshold for SQS oldest message in the queue (minutes).
# sqsAlertsOldestThreshold: 30

# Set the alert threshold for total number of SQS on the queue waiting to be processed.
# sqsAlertsTotalMessagesThreshold: 100

# To monitor AWS SNS Topic queues, add the name of the topic in a list.
# snsAlertsTopicNames:
#   topic-name-id: "Topic nice display name"
#   topic-name-2-id: "Topic nice display name 2"

# Set the alert threshold for no SNS messages published to topic (minutes).
# snsAlertsNoMessagesThresholdMinutes: 30
