# Default values for generic-prometheus-alerts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

alertSeverity: digital-prison-service

runbookUrl: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#

# Alert by default will target resources uses a regex and the application name (.Values.nameOverride).
# To be more or less specific with promql queries set these overrides in the parent chart, examples:

#podTargetOverride: ".*"

#deploymentTargetOverride: ".*"

#ingressTargetOverride: ".*"

#statefulsetTargetOverride: ".*"

#hpaTargetOverride: ".*"

#jobTargetOverride: ".*"

#cronjobTargetOverride: ".*"

extraAnnotations: {}

extraLabels:
  prometheus: cloud-platform

additionalRuleLabels: {}
