---
# Default values for generic-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: example_repo/example_image
  pullPolicy: IfNotPresent
  # image tag is overridden at deployment time using helm "--set" option
  tag: "example_app_version"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# override docker image CMD
containerArgs: []

# override docker image ENTRYPOINT
containerCommand: []

serviceAccountName: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  enabled: true
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/custom-http-errors: "418"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  host: chart-example.local
  path: /
  tlsSecretName: chart-example-tls
  # live-1 is blue, live is green
  contextColour: blue
  modsecurity_enabled: false
  modsecurity_audit_enabled: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  httpGet:
    path: /health/liveness
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10

readinessProbe:
  httpGet:
    path: /health/readiness
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 100%
    maxUnavailable: 0

env:
  "NED": "FRED"

namespace_secrets:
  ted:
    "BOB": "boss"
