{{- if .Values.elastiCacheAlertsClusterIds -}}
  {{- $targetNamespace := .Release.Namespace }}
  {{- $targetApplication := required "A value for targetApplication must be set" .Values.targetApplication }}
  {{- $elastiCacheAlertsEngineCPUThreshold := .Values.elastiCacheAlertsEngineCPUThreshold }}
  {{- $elastiCacheAlertsEngineCPUThresholdMinutes := .Values.elastiCacheAlertsEngineCPUThresholdMinutes }}
  {{- $elastiCacheAlertsCPUThreshold := .Values.elastiCacheAlertsCPUThreshold }}
  {{- $elastiCacheAlertsCPUThresholdMinutes := .Values.elastiCacheAlertsCPUThresholdMinutes }}
  {{- $elastiCacheAlertsFreeMemoryThreshold := .Values.elastiCacheAlertsFreeMemoryThreshold }}
  {{- $elastiCacheAlertsFreeMemoryThresholdMinutes := .Values.elastiCacheAlertsFreeMemoryThresholdMinutes }}
  {{- $targetApplicationBusinessHours := printf "and ON() %s:business_hours" .Values.targetApplication | replace "-" "_" }}
  {{- $businessOrAllHoursExpression := ternary $targetApplicationBusinessHours "" .Values.businessHoursOnly}}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $targetApplication }}-elasticache
  labels:
  {{- include "generic-prometheus-alerts.labels" . | nindent 4 }}
spec:
  groups:
    - name: {{ $targetApplication }}-elasticache
      rules:
        {{- range $key, $val := $.Values.elastiCacheAlertsClusterIds }}
        - alert: elasticache-enginecpu-utilisation
          annotations:
            message: elasticache cluster {{ $val }} in {{ $targetNamespace }} - Engine CPU utilisation at {{`{{`}} printf "%.2f" $value {{`}}`}} which is over threshold of {{ $elastiCacheAlertsEngineCPUThreshold }} for last {{ $elastiCacheAlertsEngineCPUThresholdMinutes }} mins. This alert configured by app {{ $targetNamespace }}/{{ $targetApplication }}.
            runbook_url: {{ $.Values.runbookUrl }}elasticache-enginecpu-utilisation
            {{/* TODO*/}}
            dashboard_url: {{ $.Values.grafanaUrl }}/d/VR46pmwWk/aws-elasticache?orgId=1&var-datasource=Cloudwatch&var-region=default&var-elasticacheclusteid={{ $key }}&from=now-6h&to=now
            summary: elasticache cluster CPU usage too high
          expr: |-
            aws_elasticache_engine_cpuutilization_maximum{cache_cluster_id='{{ $key }}'} > {{ $elastiCacheAlertsEngineCPUThreshold }}
          {{ $businessOrAllHoursExpression }}
          for: {{ $elastiCacheAlertsEngineCPUThresholdMinutes }}m
          labels:
            severity: {{ $.Values.alertSeverity }}
        - alert: elasticache-cpu-utilisation
          annotations:
            message: elasticache cluster {{ $val }} in {{ $targetNamespace }} - CPU utilisation at {{`{{`}} printf "%.2f" $value {{`}}`}} which is over threshold of {{ $elastiCacheAlertsCPUThreshold }} for last {{ $elastiCacheAlertsCPUThresholdMinutes }} mins. This alert configured by app {{ $targetNamespace }}/{{ $targetApplication }}.
            runbook_url: {{ $.Values.runbookUrl }}elasticache-cpu-utilisation
            {{/* TODO*/}}
            dashboard_url: {{ $.Values.grafanaUrl }}/d/VR46pmwWk/aws-elasticache?orgId=1&var-datasource=Cloudwatch&var-region=default&var-elasticacheclusteid={{ $key }}&from=now-6h&to=now
            summary: elasticache cluster CPU usage too high
          expr: |-
            aws_elasticache_cpuutilization_maximum{cache_cluster_id='{{ $key }}'} > {{ $elastiCacheAlertsCPUThreshold }}
          {{ $businessOrAllHoursExpression }}
          for: {{ $elastiCacheAlertsCPUThresholdMinutes }}m
          labels:
            severity: {{ $.Values.alertSeverity }}
        - alert: elasticache-memory-utilisation
          annotations:
            message: elasticache cluster {{ $val }} in {{ $targetNamespace }} - Memory utilisation at {{`{{`}} printf "%.2f" $value {{`}}`}} which is over threshold of {{ $elastiCacheAlertsFreeMemoryThreshold }} for last {{ $elastiCacheAlertsFreeMemoryThresholdMinutes }} mins. This alert configured by app {{ $targetNamespace }}/{{ $targetApplication }}.
            runbook_url: {{ $.Values.runbookUrl }}elasticache-memory-utilisation
            {{/* TODO*/}}
            dashboard_url: {{ $.Values.grafanaUrl }}/d/VR46pmwWk/aws-elasticache?orgId=1&var-datasource=Cloudwatch&var-region=default&var-elasticacheclusteid={{ $key }}&from=now-6h&to=now
            summary: elasticache cluster Memory usage too high
          expr: |-
            aws_elasticache_freeable_memory_average{cache_cluster_id='{{ $key }}'} /1000000 < {{ $elastiCacheAlertsFreeMemoryThreshold }}
          {{ $businessOrAllHoursExpression }}
          for: {{ $elastiCacheAlertsFreeMemoryThresholdMinutes }}m
          labels:
            severity: {{ $.Values.alertSeverity }}

  {{- end }}
  {{- end }}
