{{- if .Values.snsAlertsTopicNames -}}
{{- $targetApplication := required "A value for targetApplication must be set" .Values.targetApplication }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $targetApplication }}-sns
  labels:
    {{- include "generic-prometheus-alerts.labels" . | nindent 4 }}
spec:
  groups:
    - name: {{ $targetApplication }}-sns
      rules:
{{- range $.Values.snsAlertsTopicNames }}
        - alert: SNS-no-messages-published
          annotations:
            message: "SNS topic {{`{{`}} $labels.topic_name {{`}}`}} - no messages published in last 20 mins, check the producer app is healthy."
            runbook_url: {{ $.Values.runbookUrl }}sns-no-messages-published
            dashboard_url: https://grafana.live-1.cloud-platform.service.justice.gov.uk/d/AWSSNS000/dps-aws-sns?orgId=1&var-topic={{ . }}&from=now-6h&to=now
          expr: |-
            absent(aws_sns_number_of_messages_published_sum{topic_name=~".*{{ . }}"} offset 5m) == 1
          for: 20m
          labels:
            severity: {{ $.Values.alertSeverity }}
{{- end }}
{{- end }}
