{{- if .Values.rdsAlertsDatabases -}}
{{- $targetNamespace := .Release.Namespace }}
{{- $targetApplication := required "A value for targetApplication must be set" .Values.targetApplication }}
{{- $rdsAlertsCPUThreshold := .Values.rdsAlertsCPUThreshold }}
{{- $rdsAlertsCPUThresholdMinutes := .Values.rdsAlertsCPUThresholdMinutes }}
{{- $rdsAlertsConnectionThreshold := .Values.rdsAlertsConnectionThreshold }}
{{- $rdsAlertsConnectionThresholdMinutes := .Values.rdsAlertsConnectionThresholdMinutes }}
{{- $targetApplicationBusinessHours := printf "and ON() %s:business_hours" .Values.targetApplication | replace "-" "_" }}
{{- $businessOrAllHoursExpression := ternary $targetApplicationBusinessHours "" .Values.businessHoursOnly}}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $targetApplication }}-rds
  labels:
    {{- include "generic-prometheus-alerts.labels" . | nindent 4 }}
spec:
  groups:
    - name: {{ $targetApplication }}-rds
      rules:
{{- range $key, $val := $.Values.rdsAlertsDatabases }}
        - alert: rds-cpu-utilisation
          annotations:
            message: RDS database {{ $val }} in {{ $targetNamespace }} - CPU utilisation at {{`{{`}} printf "%.2f" $value {{`}}`}} which is over threshold of {{ $rdsAlertsCPUThreshold }} for last {{ $rdsAlertsCPUThresholdMinutes }} mins. This alert configured by app {{ $targetNamespace }}/{{ $targetApplication }}.
            runbook_url: {{ $.Values.runbookUrl }}rds-cpu-utilisation
            dashboard_url: {{ $.Values.grafanaUrl }}/d/VR46pmwWk/aws-rds?orgId=1&var-datasource=Cloudwatch&var-region=default&var-dbinstanceidentifier={{ $key }}&from=now-6h&to=now
            summary: RDS CPU usage too high
          expr: |-
            aws_rds_cpuutilization_average{dbinstance_identifier='{{ $key }}'} > {{ $rdsAlertsCPUThreshold }}
            {{ $businessOrAllHoursExpression }}
          for: {{ $rdsAlertsCPUThresholdMinutes }}m
          labels:
            severity: {{ $.Values.alertSeverity }}
        - alert: rds-connection-count
          annotations:
            message: RDS database {{ $val }} in {{ $targetNamespace }} - there are {{`{{`}} $value {{`}}`}} connections which is over threshold of {{ $rdsAlertsConnectionThreshold }} for last {{ $rdsAlertsConnectionThresholdMinutes }} mins. This alert configured by app {{ $targetNamespace }}/{{ $targetApplication }}.
            runbook_url: {{ $.Values.runbookUrl }}rds-connection-count
            dashboard_url: {{ $.Values.grafanaUrl }}/d/VR46pmwWk/aws-rds?orgId=1&var-datasource=Cloudwatch&var-region=default&var-dbinstanceidentifier={{ $key }}&from=now-6h&to=now
            summary: Too many RDS connections
          expr: |-
            aws_rds_database_connections_average{dbinstance_identifier='{{ $key }}'} > {{ $rdsAlertsConnectionThreshold }}
            {{ $businessOrAllHoursExpression }}
          for: {{ $rdsAlertsConnectionThresholdMinutes }}m
          labels:
            severity: {{ $.Values.alertSeverity }}
{{- end }}
{{- end }}
