{{- if .Values.elastiCacheAlertsClusterIds -}}
  {{- $targetNamespace := .Release.Namespace }}
  {{- $targetApplication := required "A value for targetApplication must be set" .Values.targetApplication }}
  {{- $elastiCacheAlertsEngineCPUThreshold := .Values.elastiCacheAlertsEngineCPUThreshold }}
  {{- $elastiCacheAlertsEngineCPUThresholdMinutes := .Values.elastiCacheAlertsEngineCPUThresholdMinutes }}
  {{- $elastiCacheAlertsCPUThreshold := .Values.elastiCacheAlertsCPUThreshold }}
  {{- $elastiCacheAlertsCPUThresholdMinutes := .Values.elastiCacheAlertsCPUThresholdMinutes }}
  {{- $elastiCacheAlertsFreeMemoryThreshold := .Values.elastiCacheAlertsFreeMemoryThreshold }}
  {{- $elastiCacheAlertsFreeMemoryThresholdMinutes := .Values.elastiCacheAlertsFreeMemoryThresholdMinutes }}
  {{- $elastiCacheAlertsMemoryUsageThreshold := .Values.elastiCacheAlertsMemoryUsageThreshold }}
  {{- $elastiCacheAlertsMemoryUsageThresholdMinutes := .Values.elastiCacheAlertsMemoryUsageThresholdMinutes }}
  {{- $targetApplicationBusinessHours := printf "and ON() %s:business_hours" .Values.targetApplication | replace "-" "_" }}
  {{- $businessOrAllHoursExpression := ternary $targetApplicationBusinessHours "" .Values.businessHoursOnly}}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $targetApplication }}-elasticache
  labels:
  {{- include "generic-prometheus-alerts.labels" . | nindent 4 }}
spec:
  groups:
    - name: {{ $targetApplication }}-elasticache
      rules:
        {{- range $clusterId, $displayName := $.Values.elastiCacheAlertsClusterIds }}
        - alert: elasticache-enginecpu-utilisation
          annotations:
            message: elasticache cluster {{ $clusterId }} in {{ $targetNamespace }} - EngineCPU utilisation at {{`{{`}} printf "%.2f" $value {{`}}`}} which is over threshold of {{ $elastiCacheAlertsEngineCPUThreshold }} for last {{ $elastiCacheAlertsEngineCPUThresholdMinutes }} mins. This alert configured by app {{ $targetNamespace }}/{{ $targetApplication }}.
            runbook_url: {{ $.Values.runbookUrl }}elasticache-enginecpu-utilisation
            dashboard_url: {{ $.Values.grafanaUrl }}/d/nK7rpiQZk/aws-elasticache-redis?orgId=1&var-cacheclusterId={{ $clusterId }}&from=now-6h&to=now
            summary: elasticache cluster EngineCPU usage too high
          expr: |-
            aws_elasticache_engine_cpuutilization_average{cache_cluster_id='{{ $clusterId }}'} offset {{ $elastiCacheAlertsEngineCPUThresholdMinutes }}m > {{ $elastiCacheAlertsEngineCPUThreshold }}
            {{ $businessOrAllHoursExpression }}
          for: {{ $elastiCacheAlertsEngineCPUThresholdMinutes }}m
          labels:
            {{- include "generic-prometheus-alerts.ruleLabels" . | nindent 12 }}

        - alert: elasticache-cpu-utilisation
          annotations:
            message: elasticache cluster {{ $clusterId }} in {{ $targetNamespace }} - CPU utilisation at {{`{{`}} printf "%.2f" $value {{`}}`}} which is over threshold of {{ $elastiCacheAlertsCPUThreshold }} for last {{ $elastiCacheAlertsCPUThresholdMinutes }} mins. This alert configured by app {{ $targetNamespace }}/{{ $targetApplication }}.
            runbook_url: {{ $.Values.runbookUrl }}elasticache-cpu-utilisation
            dashboard_url: {{ $.Values.grafanaUrl }}/d/nK7rpiQZk/aws-elasticache-redis?orgId=1&var-cacheclusterId={{ $clusterId }}&from=now-6h&to=now
            summary: elasticache cluster CPU usage too high
          expr: |-
            aws_elasticache_cpuutilization_average{cache_cluster_id='{{ $clusterId }}'} offset {{ $elastiCacheAlertsCPUThresholdMinutes }}m > {{ $elastiCacheAlertsCPUThreshold }}
            {{ $businessOrAllHoursExpression }}
          for: {{ $elastiCacheAlertsCPUThresholdMinutes }}m
          labels:
            {{- include "generic-prometheus-alerts.ruleLabels" . | nindent 12 }}

        - alert: elasticache-freeable-memory
          annotations:
            message: elasticache cluster {{ $clusterId }} in {{ $targetNamespace }} - freeable memory at {{`{{`}} printf "%.2f" $value {{`}}`}} which is below threshold of {{ $elastiCacheAlertsFreeMemoryThreshold }} for last {{ $elastiCacheAlertsFreeMemoryThresholdMinutes }} mins. This alert configured by app {{ $targetNamespace }}/{{ $targetApplication }}.
            runbook_url: {{ $.Values.runbookUrl }}elasticache-memory-utilisation
            dashboard_url: {{ $.Values.grafanaUrl }}/d/nK7rpiQZk/aws-elasticache-redis?orgId=1&var-cacheclusterId={{ $clusterId }}&from=now-6h&to=now
            summary: elasticache cluster freeable memory too low
          expr: |-
            (aws_elasticache_freeable_memory_average{cache_cluster_id='{{ $clusterId }}'} offset 5m)/1000000 < {{ $elastiCacheAlertsFreeMemoryThreshold }}
            {{ $businessOrAllHoursExpression }}
          for: {{ $elastiCacheAlertsFreeMemoryThresholdMinutes }}m
          labels:
            {{- include "generic-prometheus-alerts.ruleLabels" . | nindent 12 }}

        - alert: elasticache-memory-utilisation
          annotations:
            message: elasticache cluster {{ $clusterId }} in {{ $targetNamespace }} - memory utilisation at {{`{{`}} printf "%.2f" $value {{`}}`}} which is over threshold of {{ $elastiCacheAlertsMemoryUsageThreshold }} for last {{ $elastiCacheAlertsMemoryUsageThresholdMinutes }} mins. This alert configured by app {{ $targetNamespace }}/{{ $targetApplication }}.
            runbook_url: {{ $.Values.runbookUrl }}elasticache-memory-utilisation
            dashboard_url: {{ $.Values.grafanaUrl }}/d/nK7rpiQZk/aws-elasticache-redis?orgId=1&var-cacheclusterId={{ $clusterId }}&from=now-6h&to=now
            summary: elasticache cluster memory usage too high
          expr: |-
            aws_elasticache_database_memory_usage_percentage_average{cache_cluster_id='{{ $clusterId }}'} offset {{ $elastiCacheAlertsMemoryUsageThresholdMinutes }}m > {{ $elastiCacheAlertsMemoryUsageThreshold }}
            {{ $businessOrAllHoursExpression }}
          for: {{ $elastiCacheAlertsMemoryUsageThresholdMinutes }}m
          labels:
            {{- include "generic-prometheus-alerts.ruleLabels" . | nindent 12 }}

        {{- end }}
{{- end }}
