{{- $targetApplication := required "A value for targetApplication must be set" .Values.targetApplication }}
{{- $targetApplicationUnderscore := .Values.targetApplication | replace "-" "_" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $targetApplication }}-rules
  labels:
    {{- include "generic-prometheus-alerts.labels" . | nindent 4 }}
spec:
  groups:
    - name: {{ $targetApplication }}-rules
      rules:
        - record: {{ $targetApplicationUnderscore }}:summer_time_offset
          expr: |
            (vector(1) and (month() > 3 and month() < 10))
            or
            (vector(1) and (month() == 3 and (day_of_month() - day_of_week()) >= 25) and absent((day_of_month() >= 25) and (day_of_week() == 0)))
            or
            (vector(1) and (month() == 10 and (day_of_month() - day_of_week()) < 25) and absent((day_of_month() >= 25) and (day_of_week() == 0)))
            or
            (vector(1) and ((month() == 10 and hour() < 1) or (month() == 3 and hour() > 0)) and ((day_of_month() >= 25) and (day_of_week() == 0)))
            or
            vector(0)
        - record: {{ $targetApplicationUnderscore }}:british_time
          expr: time() + 3600 * {{ $targetApplicationUnderscore }}:summer_time_offset
        - record: {{ $targetApplicationUnderscore }}:business_day
          expr: 0 < day_of_week({{ $targetApplicationUnderscore }}:british_time) < 6
        - record: {{ $targetApplicationUnderscore }}:business_hour
          expr: 8 <= hour({{ $targetApplicationUnderscore }}:british_time) < 18
        - record: {{ $targetApplicationUnderscore }}:business_hours
          expr: {{ $targetApplicationUnderscore }}:business_hour and {{ $targetApplicationUnderscore }}:business_day
