{{- if and .Values.ingress.enabled -}}
{{- $fullName := include "generic-service.fullname" . -}}
{{- $ingressName := print $fullName "-v1-2" }}
{{- $svcPort := .Values.service.port -}}
{{- $ingressPath  := .Values.ingress.path -}}
{{- $ingressHealthPath := .Values.ingress.healthPath -}}
{{- $hosts := or .Values.ingress.hosts (list .Values.ingress.host) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingressName }}
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.allowlist }}
    {{- include "app.makeIpAllowList" . | nindent 4 }}
  {{- end }}
    external-dns.alpha.kubernetes.io/set-identifier: {{ $ingressName }}-{{ .Release.Namespace }}-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  {{- if .Values.ingress.modsecurity_enabled }}
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: {{ tpl (toYaml .Values.ingress.modsecurity_snippet) . | nindent 6 }}
  {{- end }}
spec:
  ingressClassName: {{- if .Values.ingress.className }} {{ .Values.ingress.className }} {{- else if .Values.ingress.modsecurity_enabled }} "modsec" {{- else }} "default" {{- end }}
  tls:
  - hosts:
    {{- range $hosts }}
      - {{ . }}
    {{- end }}
    {{ if .Values.ingress.tlsSecretName }}secretName: {{ .Values.ingress.tlsSecretName }}{{ end }}
  rules:
    {{- range $hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          - path: {{ $ingressHealthPath }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
    {{- end }}
{{- end }}
