{{- if and .Values.ingress.enabled .Values.ingress.dso_enabled -}}
{{- $fullName := include "generic-service.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $ingressPath  := .Values.ingress.path -}}
{{- $hosts := or .Values.ingress.hosts (list .Values.ingress.host) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.allowlist }}
    {{- include "app.makeIpAllowList" . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    {{- range $hosts }}
      - {{ . }}
    {{- end }}
    {{ if .Values.ingress.tlsSecretName }}secretName: {{ .Values.ingress.tlsSecretName }}{{ end }}
  rules:
    {{- range $hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
    {{- end }}
{{- end }}
