{{- if .Values.custommetrics.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "generic-service.fullname" . }}-monitoring
spec:
  podSelector:
    matchLabels:
      {{- include "generic-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            component: monitoring
{{- end }}
