{{- if eq .Values.ingress.enabled false -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "generic-service.fullname" . }}-monitoring
spec:
  podSelector:
    matchLabels:
      {{- include "generic-service.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          component: monitoring
{{- end -}}
