{{- if .Values.postgresDatabaseRestore.enabled -}}
{{- /*
This template creates a shell script config map and a cronjob (running every Sunday).  It should only be enabled in
the production namespace in order to copy the production database to pre-production.  This is so that the production
secrets aren't exposed outside the production namespace.

The script creates a backup of the production database in an s3 bucket.
*/}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ (.Values.postgresDatabaseRestore.backupJobName) | default (printf "%s-postgres-backup" (include "generic-service.fullname" .)) }}
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
    #!/bin/bash
    set -ue
{{ .Files.Get "prison-postgres-init.sh" | indent 4 }}
{{ .Files.Get "prison-postgres-backup.sh" | indent 4 }}

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ (.Values.postgresDatabaseRestore.backupJobName) | default (printf "%s-postgres-backup" (include "generic-service.fullname" .)) }}
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
spec:
  schedule: "30 4 * * SUN" # this must be the same time as the Sunday Oracle NOMIS backup
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      backoffLimit: 0
      activeDeadlineSeconds: {{ .Values.postgresDatabaseRestore.timeout | default 2400 }}
      template:
        spec:
          containers:
            - name: postgres-restore
              image: "{{ .Values.postgresDatabaseRestore.image }}:{{ .Values.postgresDatabaseRestore.tag }}"
              command:
                - /bin/entrypoint.sh
              volumeMounts:
                - name: {{ (.Values.postgresDatabaseRestore.backupJobName) | default (printf "%s-postgres-backup" (include "generic-service.fullname" .)) }}
                  mountPath: /bin/entrypoint.sh
                  readOnly: true
                  subPath: entrypoint.sh
              securityContext:
                {{- toYaml .Values.postgresDatabaseRestore.securityContext | nindent 16 }}
              resources:
                limits:
                  cpu: 500m
                  memory: 500Mi
                requests:
                  cpu: 500m
                  memory: 500Mi
    {{- include "postgresRestore.envs" .Values | nindent 14 }}
          restartPolicy: "Never"
          volumes:
            - name: {{ (.Values.postgresDatabaseRestore.backupJobName) | default (printf "%s-postgres-backup" (include "generic-service.fullname" .)) }}
              configMap:
                name: {{ (.Values.postgresDatabaseRestore.backupJobName) | default (printf "%s-postgres-backup" (include "generic-service.fullname" .)) }}
                defaultMode: 0755
{{- end }}
