{{- if .Values.scheduledDowntime.enabled -}}
{{- $hashServiceName  := regexReplaceAll "[^0-9]+" ((include "generic-service.fullname" .)  | sha256sum)  ""  | trunc 3 -}}
{{- $randomMinute := printf "%d" (mod (atoi $hashServiceName) 60) -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "generic-service.fullname" . | trunc 43 }}-shutdown
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.scheduledDowntime.shutdown }}
  timeZone: {{ .Values.scheduledDowntime.timeZone }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      template:
        spec:
          containers:
            - name: hmpps-devops-tools
              image: "{{ .Values.scheduledDowntime.image }}:{{ .Values.scheduledDowntime.tag }}"
              args:
                - kubectl
                - scale
                - deploy
                - {{ include "generic-service.fullname" . }}
                - --replicas=0
              securityContext:
                {{- toYaml .Values.scheduledDowntime.securityContext | nindent 16 }}
          restartPolicy: OnFailure
          serviceAccountName: {{ .Values.scheduledDowntime.serviceAccountName }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "generic-service.fullname" . | trunc 43 }}-startup
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
spec:
  schedule:  {{- if .Values.scheduledDowntime.startup }} {{ .Values.scheduledDowntime.startup }} {{- else }} {{ print $randomMinute " 6 * * 1-5" }} {{- end }}
  timeZone: {{ .Values.scheduledDowntime.timeZone }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      template:
        spec:
          containers:
            - name: hmpps-devops-tools
              image: ghcr.io/ministryofjustice/hmpps-devops-tools:latest
              args:
                - kubectl
                - scale
                - deploy
                - {{ include "generic-service.fullname" . }}
                - --replicas={{ .Values.replicaCount }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
          restartPolicy: OnFailure
          serviceAccountName: {{ .Values.scheduledDowntime.serviceAccountName }}
{{- end }}
