{{- if .Values.scheduledDowntime.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "generic-service.fullname" . | trunc 43 }}-shutdown
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.scheduledDowntime.shutdown }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      template:
        spec:
          containers:
            - name: hmpps-devops-tools
              image: "{{ .Values.scheduledDowntime.image }}:{{ .Values.scheduledDowntime.tag }}"
              args:
                - kubectl
                - scale
                - deploy
                - {{ include "generic-service.fullname" . }}
                - --replicas=0
              securityContext:
                {{- toYaml .Values.scheduledDowntime.securityContext | nindent 16 }}
          restartPolicy: OnFailure
          serviceAccountName: {{ .Values.scheduledDowntime.serviceAccountName }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "generic-service.fullname" . | trunc 43 }}-startup
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.scheduledDowntime.startup }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      template:
        spec:
          containers:
            - name: hmpps-devops-tools
              image: ghcr.io/ministryofjustice/hmpps-devops-tools:latest
              args:
                - kubectl
                - scale
                - deploy
                - {{ include "generic-service.fullname" . }}
                - --current-replicas=0
                - --replicas={{ .Values.replicaCount }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
          restartPolicy: OnFailure
          serviceAccountName: {{ .Values.scheduledDowntime.serviceAccountName }}
{{- end }}