{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{ if eq .Values.ingress.enabled false -}}
    - port: {{ .Values.service.port }}
      targetPort: proxy-http
      protocol: TCP
      name: http
    - port: {{ include "generic-service.traefikProxyMetricsPort" . }}
      targetPort: proxy-metrics
      protocol: TCP
      name: proxy-metrics
    {{- else -}}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "generic-service.selectorLabels" . | nindent 4 }}
{{- end }}
