name: Backup Repository to SharePoint

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: '10 2 * * *'

permissions: {}

jobs:
  backup:
    name: Backup to SharePoint
    runs-on: ubuntu-latest
    env:
      SP_CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
      SP_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
      AZ_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    steps:
      - name: Backup repository to SharePoint
        uses: ministryofjustice/hmpps-github-shared-actions/.github/actions/sharepoint_repository_backup@cd5eb88ee6b73a22548a64b8c7358a3bedc9516f # v1.0.13
        with:
          retention_count: 5 # optional, defaults to 5
