name: Backup Repository to SharePoint

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: '10 2 * * *'

permissions: 
  contents: read

jobs:
  backup:
    name: Backup to SharePoint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/backup_repository.yml@v2
    with:
      retention_count: 5 # optional, defaults to 5
    secrets:
      SHAREPOINT_CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
      SHAREPOINT_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
